### ISSUE TITLE
Gen

### ISSUE THREAD

**Issue by ghost** [gen2brain/x264-go#1]
What approach did you use to wrap the c code ?

C for go is one I know but really curious how you approached it

**Comment by gen2brain** [comment]
I usually use `go tool cgo -godefs` for structs, so paddings are correct and structs can be used both in C and Go. For some projects I used c-for-go as a starting point, but I don't like how result looks (references in structs and cgo_helpers), for constants it is ok (I used c-for-go here for constants).

Also, you can at least get the function names nicely formatted with c-for-go, this projects doesn't have a lot of functions  so after that I manually added code and docs from x264.h.

**Comment by gen2brain** [comment]
For https://github.com/gen2brain/raylib-go , I also had a python script that adds docs from raylib.h, because there are a lot of functions there.

**Comment by ghost** [comment]
thanks. I was wondering what the golden path is...

Is it too much to ask that you add a Make file or bash script to show how you did it with this repo ?
It maybe thats its not a one way reproducible thing ? for example, did you have to edit the code manually that you code generated ?

**Comment by gen2brain** [comment]
There is no reproducible way for this repo, I did manually edit a lot of things. c-for-go has many .yml examples you can check.

**Comment by ghost** [comment]
ok thats good to know. Was wondering. Will close this issue, and thank you for the help on this..
