### ISSUE TITLE
fail to build on arm64

### ISSUE THREAD

**Issue by dlworld** [gen2brain/x264-go#10]
/tmp/go-build637060393/b298/_x003.o:/home/ubuntu/go/pkg/mod/github.com/gen2brain/x264-go@v0.0.0-20200517120223-c08131f6fc8a/x264c/external/x264/encoder/cabac.c:89: more undefined references to `x264_cabac_encode_decision_asm' follow
/tmp/go-build637060393/b298/_x003.o: In function `x264_cabac_mb_type_intra':
../../../../pkg/mod/github.com/gen2brain/x264-go@v0.0.0-20200517120223-c08131f6fc8a/x264c/external/x264/encoder/cabac.c:54: undefined reference to `x264_cabac_encode_terminal_asm'
../../../../pkg/mod/github.com/gen2brain/x264-go@v0.0.0-20200517120223-c08131f6fc8a/x264c/external/x264/encoder/cabac.c:56: undefined reference to `x264_cabac_encode_decision_asm'
../../../../pkg/mod/github.com/gen2brain/x264-go@v0.0.0-20200517120223-c08131f6fc8a/x264c/external/x264/encoder/cabac.c:58: undefined reference to `x264_cabac_encode_decision_asm'
../../../../pkg/mod/github.com/gen2brain/x264-go@v0.0.0-20200517120223-c08131f6fc8a/x264c/external/x264/encoder/cabac.c:64: undefined reference to `x264_cabac_encode_decision_asm'
../../../../pkg/mod/github.com/gen2brain/x264-go@v0.0.0-20200517120223-c08131f6fc8a/x264c/external/x264/encoder/cabac.c:65: undefined reference to `x264_cabac_encode_decision_asm'
/tmp/go-build637060393/b298/_x003.o: In function `x264_cabac_transform_size':
../../../../pkg/mod/github.com/gen2brain/x264-go@v0.0.0-20200517120223-c08131f6fc8a/x264c/external/x264/encoder/cabac.c:238: undefined reference to `x264_cabac_encode_decision_asm'
/tmp/go-build637060393/b298/_x003.o:/home/ubuntu/go/pkg/mod/github.com/gen2brain/x264-go@v0.0.0-20200517120223-c08131f6fc8a/x264c/external/x264/encoder/cabac.c:89: more undefined references to `x264_cabac_encode_decision_asm' follow
/tmp/go-build637060393/b298/_x003.o: In function `x264_slice_write':
../../../../pkg/mod/github.com/gen2brain/x264-go@v0.0.0-20200517120223-c08131f6fc8a/x264c/external/x264/encoder/encoder.c:2748: undefined reference to `x264_cabac_encode_terminal_asm'
collect2: error: ld returned 1 exit status
# github.com/gen2brain/x264-go/x264c

**Comment by gen2brain** [comment]
It is always useful to paste context, how, what, when, etc. from your logs it seems you are using assembler, e.g. lib compiled with ASM, code included in this repo is C only, so are you using external lib, etc. nothing can be concluded from this issue.

**Comment by gen2brain** [comment]
It should be fixed in https://github.com/gen2brain/x264-go/commit/e6c5f92ae3693f2da778b1821e1b03e0db119942 , works in my test build.
