### ISSUE TITLE
Is there a way to support hardware acceleration

### ISSUE THREAD

**Issue by SolskGaer** [gen2brain/x264-go#11]
In my case, the speed of encoding become the bottle of the whole process, it takes about 50ms to encode a single image in ultrafast preset. Is there a way to use hardware acceleration? Or any other way to speed up encoding?

**Comment by gen2brain** [comment]
Included is only C code, you can use `extlib` tag and link with your external library, that is usually built with ASM optimizations, that should work faster.

**Comment by gen2brain** [comment]
@SolskGaer Did you measure the speed difference in encoding with the external library?

**Comment by SolskGaer** [comment]
@gen2brain sorry for the delayed reply. could you be more specific? I know little about the c programming language and don't know how to do it.

**Comment by gen2brain** [comment]
No problems, anyway currently `-tags extlib` doesn't work with the latest library, it needs to be compiled with the exact same version.  I Will try to update everything when I find the time.

**Comment by SolskGaer** [comment]
@gen2brain thanks a lot, could you give me some guidance on the knowledges that you mentioned? I want to learn those things myself.

**Comment by gen2brain** [comment]
External library functions again. Build with `-tags extlib` and use your installed x264 library.
