### ISSUE TITLE
the efficiency of YCbCr converter in x264-go

### ISSUE THREAD

**Issue by hwwxj** [gen2brain/x264-go#14]
hello

I found that the efficiency of YCbCr converter in x264-go is quite low,

![image](https://user-images.githubusercontent.com/33884571/106913882-6e88ed00-673f-11eb-9c66-54e19ee4978f.png)

I0204 23:05:53.512131 31980 encoder.go:79] H264： start encode one image
before convert to YCbCr. the time is %v 2021-02-04 23:05:53.512142829 +0800 CST m=+17.347932716
after convert to YCbCr. the time is %v 2021-02-04 23:05:53.663298327 +0800 CST m=+17.499088233

I0204 23:05:53.669515 31980 encoder.go:79] H264： start encode one image
before convert to YCbCr. the time is %v 2021-02-04 23:05:53.66953006 +0800 CST m=+17.505319930
after convert to YCbCr. the time is %v 2021-02-04 23:05:53.826771366 +0800 CST m=+17.662561280

1080p
convert time：almost 151ms
convert + encode time : 157ms

Is there any methods to optimize?

**Comment by Nv7-GitHub** [comment]
the conversion is done with `draw.Draw`, there would need to be manual (direct) conversion for higher performance

**Comment by gen2brain** [comment]
I saw an example in C of how to do the conversion in a more optimized way. The priority for me is to update C sources and to create a custom/merged file where `.syso` files will not be needed anymore since it breaks the external library. After that, I will see to optimize this. Not sure when will I find time though, but it is on my TODO list.

**Comment by gen2brain** [comment]
It should be slightly better with https://github.com/gen2brain/x264-go/commit/60a3411f0436c1324fa1481805191483dd2c6cde

**Comment by gen2brain** [comment]
Conversion is optimized in https://github.com/gen2brain/x264-go/commit/54bdbefd121263644719759c9432092029ee8289. Now  convert+encode time is around 35ms in screengrab example, same is with `-tags extlib`.
