### ISSUE TITLE
Doesn't produce a valid video file

### ISSUE THREAD

**Issue by Nv7-GitHub** [gen2brain/x264-go#15]
The video produced doesn't work with Quicktime or VLC. However, when I ran it through ffmpeg, ffmpeg produced a valid video. But I can't have it re-encoded through ffmpeg all the time, what is wrong? 

When I tried to run it through ffmpeg without re-encoding, ffmpeg gave the error
```
Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
```
Is there an issue with the timestamps that is causing this? I noticed that `param.ITimebaseNum` isn't set.

**Comment by gen2brain** [comment]
The result is a raw valid `.264` file. MPlayer/mpv etc. can play raw video file. It can be muxed to mp4 with ffmpeg. See https://github.com/gen2brain/x264-go/issues/2.

**Comment by Nv7-GitHub** [comment]
Ah, I thought that this was for mp4s. Do you have any recommendations for encoding to an mp4 in Go?

**Comment by gen2brain** [comment]
mp4 is just a container, same as avi, audio and video format inside can be h264, aac, etc. You just need to mux the result to mp4 as in issue #2. There are some JS muxers if you need to do that on the web, or FFmpeg from the console.

**Comment by Nv7-GitHub** [comment]
I want this to be completely self-contained - I want to be able to send this to anyone with the same OS as me and have it work, without them having to install ffmpeg or anything. Are there any solutions that are like this? Any libraries?

**Comment by gen2brain** [comment]
No idea, probably some wrapper library for FFMpeg.
