### ISSUE TITLE
Build issue - 'external/x264/common/base.c' file not found

### ISSUE THREAD

**Issue by araufdogan** [gen2brain/x264-go#18]
Hello,

I'm using m1 mac.
export GOOS=darwin
export GOARCH=arm64

When I try to build I'm getting the error 

```# github.com/gen2brain/x264-go/x264c
vendor/github.com/gen2brain/x264-go/x264c/common_base.go:6:10: fatal error: 'external/x264/common/base.c' file not found
#include "external/x264/common/base.c"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

How can I solve this error?

**Comment by gen2brain** [comment]
Don't use vendoring, it looks like you are missing whole external directory. Or use external library.

**Comment by araufdogan** [comment]
@gen2brain  It worked when I delete vendor dictionary thank you.

Another question, when I try to build linux amd64 on m1 mac, its giving an error 
```
# github.com/gen2brain/x264-go/yuv
/go/pkg/mod/github.com/gen2brain/x264-go/yuv@v0.0.0-20211014010035-0051007e2ad5/options.go:4:11: undefined: ChromaPos
/go/pkg/mod/github.com/gen2brain/x264-go/yuv@v0.0.0-20211014010035-0051007e2ad5/options.go:29:17: undefined: ChromaPos
```
Should I use linux for this or is there any solution?

**Comment by gen2brain** [comment]
The solution is to use the toolchain/compiler for that system/arch, e.g. for Windows, it would be `CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 go build `. You didn't mention how are you trying to build, of course, you cannot just change GOOS/GOARCH and expect it to work.

Not sure about the toolchain for Linux on macOS, can clang do that? Are there any profiles/targets in clang for that, like for example `--target=armv7a-linux-androideabi16` etc. All this has everything to do with C and almost nothing with Go.

**Comment by gen2brain** [comment]
You can try with `CC="clang --target=x86_64-pc-linux-gnu"`, no idea if that will work, I rarely used clang.
