### ISSUE TITLE
x264c.Param outdated?

### ISSUE THREAD

**Issue by Bun** [gen2brain/x264-go#20]
It seems the Param type is missing a number of fields that were added in the code update commits (i_bitdepth, i_avcintra_flavor, mastering_display, etc, etc), which makes the type incorrect and unable to apply most parameters correctly.

Do you perhaps have any tooling to update these types?

**Comment by gen2brain** [comment]
Thanks for reporting. I don't have time to check that currently, I will check this when I find the time. In the meantime PR to fix this is welcome. There is no special tolling but `go tool cgo -godefs` can be used for that.

**Comment by gen2brain** [comment]
This should be fixed in https://github.com/gen2brain/x264-go/commit/a0a7bbb625389d9d5aa1e1b61ff642e027eebb2b. Can you please test?
