### ISSUE TITLE
x264_config.h not found

### ISSUE THREAD

**Issue by ninja18** [gen2brain/x264-go#22]
Go version: 1.19.3
x264-go version: v0.2.0
OS version: Windows 10 version 22H2
Hi, When I try to build my project which uses x264-go with above configuration on windows it fails with this error 
```
# [github.com/gen2brain/x264-go/x264c](http://github.com/gen2brain/x264-go/x264c)
In file included from ./external/x264/common/osdep.h:52,
                 from ./external/x264/common/base.h:43,
                 from ./external/x264/common/base.c:27,
                 from ..\..\..\..\go\pkg\mod\[github.com](http://github.com/)\gen2brain\x264-go\x264c@v0.0.0-20220830082553-c054a20cbf93\common_base.go:7:
..\..\..\..\go\pkg\mod\[github.com](http://github.com/)\gen2brain\x264-go\x264c@v0.0.0-20220830082553-c054a20cbf93\external\x264/x264.h:46:10: fatal error: x264_config.h: No such file or directory
   46 | #include "x264_config.h"
```

I notice this in the `x264c@v0.0.0-20220830082553-c054a20cbf93` version of the library but in `x264-go/x264c v0.0.0-20210523185153-54bdbefd1212` this version, the same file  which has ` //#include "x264_config.h"` line commented so this version works fine while building with go 1.16 version. 

But now I can't force go to download the older version as its a indirect dependency and it always pulls the latest version of `x264c`.
Thanks

**Comment by ghp3000** [comment]
Me too.
In file included from ./external/x264/common/osdep.h:52,
                 from ./external/x264/common/base.h:43,
                 from ./external/x264/common/base.c:27,
                 from ..\go\pkg\mod\github.com\gen2brain\x264-go\x264c@v0.0.0-20220830082553-c054a20cbf93\common_base.go:7:
..\go\pkg\mod\github.com\gen2brain\x264-go\x264c@v0.0.0-20220830082553-c054a20cbf93\external\x264/x264.h:46:10: fatal error: x264_config.h: No such file or directory
   46 | #include "x264_config.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.

**Comment by gen2brain** [comment]
Thanks for reporting. This should be fixed in https://github.com/gen2brain/x264-go/commit/f7eb4bd107c621321ab2b3e53837219905f93254. The build only tested `extlib` case so this went unnoticed.
