### ISSUE TITLE
Tag with the current commit

### ISSUE THREAD

**Issue by kercre123** [gen2brain/x264-go#24]
The command `go get -u "github.com/gen2brain/x264-go"` is currently broken. I believe this was fixed in the latest commit, but the changes have not been pushed to pkg.go.dev because the current tagged version is from before the commit was made.

This is the full error:

```
go: downloading github.com/gen2brain/x264-go v0.2.2
go: github.com/gen2brain/x264-go@v0.2.2 requires
	github.com/gen2brain/x264-go/x264c@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by gen2brain** [comment]
Hi, I added the new tag, it would probably need some time for pkg.go.dev to update, not sure how exactly that works. I guess you could have just used @latest to pick the latest changes from the repo.
