### ISSUE TITLE
How can i extract seprate SPS and PPS bytes array ? 

### ISSUE THREAD

**Issue by rpatidar** [gen2brain/x264-go#25]
I am looking  to integrate the X264 with the simple-rtsp-server (mediamtx ) now to publish the x264 stream . 

 RTSP Streaming somewhere expect a separate byte array for SPS and PPS. i can see the initial header we are writing the data but its looks like its a combined data is there anyway i can seprate them up in the two parts.

**Comment by gen2brain** [comment]
@rpatidar Use the underlying `x264c` package where you can do what you want with x264. EncoderHeaders function returns SPS and PPS that will be used for the whole stream.
