### ISSUE TITLE
If I imitate NewBuffer and implement an io.Writer by myself, will it be possible to provide h264 bare streams?

### ISSUE THREAD

**Issue by nnnpa31** [gen2brain/x264-go#27]
Thank you for writing this wrapper, I would like to ask the question as the title.
Also, does it help to reduce the latency if I call `enc.Flush()` once after encoding each frame?

**Comment by gen2brain** [comment]
Not sure how that is going to help you, did you check the code? Anyway, these are bindings for x264, use the underlying `x264c` package where you can do what is possible with x264 API. Sorry, this is for issues, I don't have time for questions, for Flush, test and see if it helps.
