### ISSUE TITLE
error running example on windows

### ISSUE THREAD

**Issue by kalmastenitin** [gen2brain/x264-go#29]
I copied the example from folder and just an go mod tidy and run it using go run main.go it gives this error. 
i am not able to identify issue with package

![image](https://github.com/gen2brain/x264-go/assets/17327672/5ee8fbbb-700e-468b-8bb2-e404f2a68adc)

**Comment by gen2brain** [comment]
You are either missing a C compiler or trying to compile with `CGO_ENABLED=0`.

**Comment by kalmastenitin** [comment]
Thank You for the response. I used [tdm-gcc](https://jmeubank.github.io/tdm-gcc/) Compiler to compile with CGO_ENABLED=1 and it worked.
Closing This issue.
