### ISSUE TITLE
undefined reference to `__log2f_finite'

### ISSUE THREAD

**Issue by forevernull** [gen2brain/x264-go#6]
when i run: 
    ` go get -u github.com/gen2brain/x264-go`
then get the follow errors:
```
# github.com/gen2brain/x264-go/x264c
x264c_analyse_linux_amd64.syso: In function `x264_analyse_init_costs':
analyse.c:(.text+0x27115): undefined reference to `__log2f_finite'
collect2: ld 返回 1
```

**Comment by elie-g** [comment]
I also have this issue. Is there any workaround?

**Comment by gen2brain** [comment]
@DrunkenPoney the workaround would be to use `-tags extlib` and your external library. However, this should be fixed now in https://github.com/gen2brain/x264-go/commit/c08131f6fc8a2ff68afd41d72a4717fe1e509e08 so please check.

**Comment by gen2brain** [comment]
Fixed also for linux/386.
